name: table_calendar_null_safe
description: Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
version: 2.0.0
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
